import pytest
from Web_crawler import site_map, site_map_inside


@pytest.mark.parametrize('url, expected_result', [
    ('https://azumbrunnen.me/', {'https://azumbrunnen.me/':
         {'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
          'links': {'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
                    'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
                    'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
                    'https://azumbrunnen.me/blog/designing-expectations/',
                    'https://azumbrunnen.me/#next',
                    'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
                    'https://azumbrunnen.me/',
                    'https://azumbrunnen.me/blog/stop-talking-start-listening/',
                    'https://azumbrunnen.me/blog/the-art-of-the-button/',
                    'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
                    'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
                    'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
                    'https://azumbrunnen.me/blog/via-negativa/',
                    'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
                    'https://azumbrunnen.me/#prev',
                    'https://azumbrunnen.me/blog/the-illusion-of-time/',
                    'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
                    'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
                    'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
                    'https://azumbrunnen.me/blog/caveats-of-motion-design/',
                    'https://azumbrunnen.me/blog/why-small-teams-win/',
                    'https://azumbrunnen.me/blog/deceptive-simplicity/',
                    'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
                    'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
                    'https://azumbrunnen.me/#contact',
                    'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
                    'https://azumbrunnen.me/blog/transitions-in-ux-design/',
                    'https://azumbrunnen.me/blog/interactive-float-labels/',
                    'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
                    'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
                    'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
                    'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
                    'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
                    'https://azumbrunnen.me/blog/hover-states/',
                    'https://azumbrunnen.me/blog/designing-with-purpose/',
                    'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
     'https://azumbrunnen.me/#contact':
         {'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
          'links': {'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
                    'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
                    'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
                    'https://azumbrunnen.me/blog/designing-expectations/',
                    'https://azumbrunnen.me/#next',
                    'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
                    'https://azumbrunnen.me/',
                    'https://azumbrunnen.me/blog/stop-talking-start-listening/',
                    'https://azumbrunnen.me/blog/the-art-of-the-button/',
                    'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
                    'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
                    'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
                    'https://azumbrunnen.me/blog/via-negativa/',
                    'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
                    'https://azumbrunnen.me/#prev',
                    'https://azumbrunnen.me/blog/the-illusion-of-time/',
                    'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
                    'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
                    'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
                    'https://azumbrunnen.me/blog/caveats-of-motion-design/',
                    'https://azumbrunnen.me/blog/why-small-teams-win/',
                    'https://azumbrunnen.me/blog/deceptive-simplicity/',
                    'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
                    'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
                    'https://azumbrunnen.me/#contact',
                    'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
                    'https://azumbrunnen.me/blog/transitions-in-ux-design/',
                    'https://azumbrunnen.me/blog/interactive-float-labels/',
                    'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
                    'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
                    'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
                    'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
                    'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
                    'https://azumbrunnen.me/blog/hover-states/',
                    'https://azumbrunnen.me/blog/designing-with-purpose/',
                    'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
     'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/': {
         'title': 'Creating distraction-free reading experiences — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/#articles':
         {'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
          'links': {'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
                    'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
                    'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
                    'https://azumbrunnen.me/blog/designing-expectations/',
                    'https://azumbrunnen.me/#next',
                    'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
                    'https://azumbrunnen.me/',
                    'https://azumbrunnen.me/blog/stop-talking-start-listening/',
                    'https://azumbrunnen.me/blog/the-art-of-the-button/',
                    'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
                    'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
                    'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
                    'https://azumbrunnen.me/blog/via-negativa/',
                    'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
                    'https://azumbrunnen.me/#prev',
                    'https://azumbrunnen.me/blog/the-illusion-of-time/',
                    'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
                    'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
                    'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
                    'https://azumbrunnen.me/blog/caveats-of-motion-design/',
                    'https://azumbrunnen.me/blog/why-small-teams-win/',
                    'https://azumbrunnen.me/blog/deceptive-simplicity/',
                    'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
                    'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
                    'https://azumbrunnen.me/#contact',
                    'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
                    'https://azumbrunnen.me/blog/transitions-in-ux-design/',
                    'https://azumbrunnen.me/blog/interactive-float-labels/',
                    'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
                    'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
                    'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
                    'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
                    'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
                    'https://azumbrunnen.me/blog/hover-states/',
                    'https://azumbrunnen.me/blog/designing-with-purpose/',
                    'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
     'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/': {
         'title': 'From Clockworks, to Computers on our Wrists — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/': {
         'title': 'The rise of Anti-Notifications — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/via-negativa/':
         {'title': 'Via Negativa — Adrian Zumbrunnen',
          'links': {'https://azumbrunnen.me/',
                    'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/why-small-teams-win/': {
         'title': 'Why Small Teams Win — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/': {
         'title': 'The Vicious Circle of Mediocre Work — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/': {
         'title': 'What designers can learn from the iPhone X — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/': {
         'title': 'Skeuomorphism In Conversational Design — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/': {
         'title': 'Taking responsibility for the things you launch — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/stop-talking-start-listening/': {
         'title': 'Stop talking, start listening — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/caveats-of-motion-design/': {
         'title': 'Caveats of Motion Design — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/': {
         'title': 'My Chatbot found my wallet — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/introducing-the-ux-bear/': {
         'title': 'Introducing the UX Bear — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/': {
         'title': 'Technical and social challenges of conversational design — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/': {
         'title': 'Are Chatbots The Future Of Web Design? — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/designing-with-purpose/': {
         'title': 'Designing with purpose — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/hover-states/': {
         'title': 'On hover states — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/the-illusion-of-time/': {
         'title': 'The illusion of time — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/deceptive-simplicity/': {
         'title': 'Deceptive Simplicity — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/blog/deceptive-simplicity/#f1',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/deceptive-simplicity/#f1': {
         'title': 'Deceptive Simplicity — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/blog/deceptive-simplicity/#f1',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/interactive-float-labels/': {
         'title': 'Interactive float-labels — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/the-self-actualizing-designer/': {
         'title': 'The self-actualizing designer — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/improving-the-hamburger-button/': {
         'title': 'Improving the hamburger button — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/': {
         'title': 'Skype’s premium strategy: no strategy — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/designing-expectations/': {
         'title': 'Designing Expectations — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/the-art-of-the-button/': {
         'title': 'The art of the button — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/transitions-in-ux-design/': {
         'title': 'Transitions in UX / UI design — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/simple-does-not-mean-boring/': {
         'title': 'Simple ain’t boring — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/',
                   'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/': {
         'title': 'Progressive Reduction: just another buzzword? — Adrian Zumbrunnen',
         'links': {
         'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/www.twitter.com/simonraess',
         'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/www.twitter.com/simonraess': {
         'title': 'azumbrunnen - Blog'},
     'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/': {
         'title': 'Gangnam Design vs Lasting Design — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/': {
         'title': 'Building progressively enhanced websites using bulletproof Backbone & CSS transforms — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/': {
         'title': 'How to work on weekends without losing your soul and your friends: The 1 charge cycle. — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/': {
         'title': 'Redefining the online identity of an advertising agency — Adrian Zumbrunnen',
         'links': {'https://azumbrunnen.me/', 'https://azumbrunnen.me/#articles'}},
     'https://azumbrunnen.me/#next': {'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
          'links': {
          'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
          'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
          'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
          'https://azumbrunnen.me/blog/designing-expectations/',
          'https://azumbrunnen.me/#next',
          'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
          'https://azumbrunnen.me/',
          'https://azumbrunnen.me/blog/stop-talking-start-listening/',
          'https://azumbrunnen.me/blog/the-art-of-the-button/',
          'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
          'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
          'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
          'https://azumbrunnen.me/blog/via-negativa/',
          'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
          'https://azumbrunnen.me/#prev',
          'https://azumbrunnen.me/blog/the-illusion-of-time/',
          'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
          'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
          'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
          'https://azumbrunnen.me/blog/caveats-of-motion-design/',
          'https://azumbrunnen.me/blog/why-small-teams-win/',
          'https://azumbrunnen.me/blog/deceptive-simplicity/',
          'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
          'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
          'https://azumbrunnen.me/#contact',
          'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
          'https://azumbrunnen.me/blog/transitions-in-ux-design/',
          'https://azumbrunnen.me/blog/interactive-float-labels/',
          'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
          'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
          'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
          'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
          'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
          'https://azumbrunnen.me/blog/hover-states/',
          'https://azumbrunnen.me/blog/designing-with-purpose/',
          'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
'https://azumbrunnen.me/#prev': {'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
          'links': {
          'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
          'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
          'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
          'https://azumbrunnen.me/blog/designing-expectations/',
          'https://azumbrunnen.me/#next',
          'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
          'https://azumbrunnen.me/',
          'https://azumbrunnen.me/blog/stop-talking-start-listening/',
          'https://azumbrunnen.me/blog/the-art-of-the-button/',
          'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
          'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
          'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
          'https://azumbrunnen.me/blog/via-negativa/',
          'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
          'https://azumbrunnen.me/#prev',
          'https://azumbrunnen.me/blog/the-illusion-of-time/',
          'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
          'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
          'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
          'https://azumbrunnen.me/blog/caveats-of-motion-design/',
          'https://azumbrunnen.me/blog/why-small-teams-win/',
          'https://azumbrunnen.me/blog/deceptive-simplicity/',
          'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
          'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
          'https://azumbrunnen.me/#contact',
          'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
          'https://azumbrunnen.me/blog/transitions-in-ux-design/',
          'https://azumbrunnen.me/blog/interactive-float-labels/',
          'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
          'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
          'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
          'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
          'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
          'https://azumbrunnen.me/blog/hover-states/',
          'https://azumbrunnen.me/blog/designing-with-purpose/',
          'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}}}
     ),
    ('http://fagaagfas.com', {})
])
def test_site_map(url, expected_result):
    result = site_map(url)
    assert result == expected_result


@pytest.mark.parametrize('url, map, domain, i, expected_result', [
    ('https://azumbrunnen.me/', {}, 'https://azumbrunnen.me/', 1,
     {'https://azumbrunnen.me/':
                                                                       {
       'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
       'links': {
       'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
       'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
       'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
       'https://azumbrunnen.me/blog/designing-expectations/',
       'https://azumbrunnen.me/#next',
       'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
       'https://azumbrunnen.me/',
       'https://azumbrunnen.me/blog/stop-talking-start-listening/',
       'https://azumbrunnen.me/blog/the-art-of-the-button/',
       'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
       'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
       'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
       'https://azumbrunnen.me/blog/via-negativa/',
       'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
       'https://azumbrunnen.me/#prev',
       'https://azumbrunnen.me/blog/the-illusion-of-time/',
       'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
       'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
       'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
       'https://azumbrunnen.me/blog/caveats-of-motion-design/',
       'https://azumbrunnen.me/blog/why-small-teams-win/',
       'https://azumbrunnen.me/blog/deceptive-simplicity/',
       'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
       'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
       'https://azumbrunnen.me/#contact',
       'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
       'https://azumbrunnen.me/blog/transitions-in-ux-design/',
       'https://azumbrunnen.me/blog/interactive-float-labels/',
       'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
       'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
       'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
       'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
       'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
       'https://azumbrunnen.me/blog/hover-states/',
       'https://azumbrunnen.me/blog/designing-with-purpose/',
       'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
'https://azumbrunnen.me/#contact':
   {
       'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
       'links': {
       'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
       'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
       'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
       'https://azumbrunnen.me/blog/designing-expectations/',
       'https://azumbrunnen.me/#next',
       'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
       'https://azumbrunnen.me/',
       'https://azumbrunnen.me/blog/stop-talking-start-listening/',
       'https://azumbrunnen.me/blog/the-art-of-the-button/',
       'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
       'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
       'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
       'https://azumbrunnen.me/blog/via-negativa/',
       'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
       'https://azumbrunnen.me/#prev',
       'https://azumbrunnen.me/blog/the-illusion-of-time/',
       'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
       'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
       'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
       'https://azumbrunnen.me/blog/caveats-of-motion-design/',
       'https://azumbrunnen.me/blog/why-small-teams-win/',
       'https://azumbrunnen.me/blog/deceptive-simplicity/',
       'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
       'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
       'https://azumbrunnen.me/#contact',
       'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
       'https://azumbrunnen.me/blog/transitions-in-ux-design/',
       'https://azumbrunnen.me/blog/interactive-float-labels/',
       'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
       'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
       'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
       'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
       'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
       'https://azumbrunnen.me/blog/hover-states/',
       'https://azumbrunnen.me/blog/designing-with-purpose/',
       'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/': {
   'title': 'Creating distraction-free reading experiences — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/#articles':
   {
       'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
       'links': {
       'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
       'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
       'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
       'https://azumbrunnen.me/blog/designing-expectations/',
       'https://azumbrunnen.me/#next',
       'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
       'https://azumbrunnen.me/',
       'https://azumbrunnen.me/blog/stop-talking-start-listening/',
       'https://azumbrunnen.me/blog/the-art-of-the-button/',
       'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
       'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
       'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
       'https://azumbrunnen.me/blog/via-negativa/',
       'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
       'https://azumbrunnen.me/#prev',
       'https://azumbrunnen.me/blog/the-illusion-of-time/',
       'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
       'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
       'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
       'https://azumbrunnen.me/blog/caveats-of-motion-design/',
       'https://azumbrunnen.me/blog/why-small-teams-win/',
       'https://azumbrunnen.me/blog/deceptive-simplicity/',
       'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
       'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
       'https://azumbrunnen.me/#contact',
       'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
       'https://azumbrunnen.me/blog/transitions-in-ux-design/',
       'https://azumbrunnen.me/blog/interactive-float-labels/',
       'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
       'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
       'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
       'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
       'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
       'https://azumbrunnen.me/blog/hover-states/',
       'https://azumbrunnen.me/blog/designing-with-purpose/',
       'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/': {
   'title': 'From Clockworks, to Computers on our Wrists — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/': {
   'title': 'The rise of Anti-Notifications — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/via-negativa/':
   {'title': 'Via Negativa — Adrian Zumbrunnen',
    'links': {'https://azumbrunnen.me/',
              'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/why-small-teams-win/': {
   'title': 'Why Small Teams Win — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/': {
   'title': 'The Vicious Circle of Mediocre Work — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/': {
   'title': 'What designers can learn from the iPhone X — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/': {
   'title': 'Skeuomorphism In Conversational Design — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/': {
   'title': 'Taking responsibility for the things you launch — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/stop-talking-start-listening/': {
   'title': 'Stop talking, start listening — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/caveats-of-motion-design/': {
   'title': 'Caveats of Motion Design — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/': {
   'title': 'My Chatbot found my wallet — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/introducing-the-ux-bear/': {
   'title': 'Introducing the UX Bear — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/': {
   'title': 'Technical and social challenges of conversational design — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/': {
   'title': 'Are Chatbots The Future Of Web Design? — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/designing-with-purpose/': {
   'title': 'Designing with purpose — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/hover-states/': {
   'title': 'On hover states — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/the-illusion-of-time/': {
   'title': 'The illusion of time — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/deceptive-simplicity/': {
   'title': 'Deceptive Simplicity — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/blog/deceptive-simplicity/#f1',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/deceptive-simplicity/#f1': {
   'title': 'Deceptive Simplicity — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/blog/deceptive-simplicity/#f1',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/interactive-float-labels/': {
   'title': 'Interactive float-labels — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/the-self-actualizing-designer/': {
   'title': 'The self-actualizing designer — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/improving-the-hamburger-button/': {
   'title': 'Improving the hamburger button — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/': {
   'title': 'Skype’s premium strategy: no strategy — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/designing-expectations/': {
   'title': 'Designing Expectations — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/the-art-of-the-button/': {
   'title': 'The art of the button — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/transitions-in-ux-design/': {
   'title': 'Transitions in UX / UI design — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/simple-does-not-mean-boring/': {
   'title': 'Simple ain’t boring — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/': {
   'title': 'Progressive Reduction: just another buzzword? — Adrian Zumbrunnen',
   'links': {
       'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/www.twitter.com/simonraess',
       'https://azumbrunnen.me/',
   'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/www.twitter.com/simonraess': {
   'title': 'azumbrunnen - Blog'},
'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/': {
   'title': 'Gangnam Design vs Lasting Design — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/': {
   'title': 'Building progressively enhanced websites using bulletproof Backbone & CSS transforms — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/': {
   'title': 'How to work on weekends without losing your soul and your friends: The 1 charge cycle. — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/': {
   'title': 'Redefining the online identity of an advertising agency — Adrian Zumbrunnen',
   'links': {'https://azumbrunnen.me/',
             'https://azumbrunnen.me/#articles'}},
'https://azumbrunnen.me/#next': {
   'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
   'links': {
       'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
       'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
       'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
       'https://azumbrunnen.me/blog/designing-expectations/',
       'https://azumbrunnen.me/#next',
       'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
       'https://azumbrunnen.me/',
       'https://azumbrunnen.me/blog/stop-talking-start-listening/',
       'https://azumbrunnen.me/blog/the-art-of-the-button/',
       'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
       'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
       'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
       'https://azumbrunnen.me/blog/via-negativa/',
       'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
       'https://azumbrunnen.me/#prev',
       'https://azumbrunnen.me/blog/the-illusion-of-time/',
       'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
       'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
       'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
       'https://azumbrunnen.me/blog/caveats-of-motion-design/',
       'https://azumbrunnen.me/blog/why-small-teams-win/',
       'https://azumbrunnen.me/blog/deceptive-simplicity/',
       'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
       'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
       'https://azumbrunnen.me/#contact',
       'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
       'https://azumbrunnen.me/blog/transitions-in-ux-design/',
       'https://azumbrunnen.me/blog/interactive-float-labels/',
       'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
       'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
       'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
       'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
       'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
       'https://azumbrunnen.me/blog/hover-states/',
       'https://azumbrunnen.me/blog/designing-with-purpose/',
       'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}},
'https://azumbrunnen.me/#prev': {
   'title': 'Adrian Zumbrunnen - UX / UI / WEB DESIGN',
   'links': {
       'https://azumbrunnen.me/blog/skypes-premium-strategy-no-strategy/',
       'https://azumbrunnen.me/blog/technical-and-social-challenges-of-conversational-design/',
       'https://azumbrunnen.me/blog/skeuomorphism-in-conversational-design/',
       'https://azumbrunnen.me/blog/designing-expectations/',
       'https://azumbrunnen.me/#next',
       'https://azumbrunnen.me/blog/progressive-reduction-just-another-buzzword/',
       'https://azumbrunnen.me/',
       'https://azumbrunnen.me/blog/stop-talking-start-listening/',
       'https://azumbrunnen.me/blog/the-art-of-the-button/',
       'https://azumbrunnen.me/blog/gangnam-design-vs-lasting-design/',
       'https://azumbrunnen.me/blog/simple-does-not-mean-boring/',
       'https://azumbrunnen.me/blog/improving-the-hamburger-button/',
       'https://azumbrunnen.me/blog/via-negativa/',
       'https://azumbrunnen.me/blog/the-vicious-circle-of-mediocre-work/',
       'https://azumbrunnen.me/#prev',
       'https://azumbrunnen.me/blog/the-illusion-of-time/',
       'https://azumbrunnen.me/blog/are-chatbots-really-the-future-of-web-design/',
       'https://azumbrunnen.me/blog/my-chatbot-found-my-wallet/',
       'https://azumbrunnen.me/blog/redefining-the-online-identity-of-an-advertising-agency/',
       'https://azumbrunnen.me/blog/caveats-of-motion-design/',
       'https://azumbrunnen.me/blog/why-small-teams-win/',
       'https://azumbrunnen.me/blog/deceptive-simplicity/',
       'https://azumbrunnen.me/blog/from-clockworks-to-computers-on-our-wrists-the-rise-of-apple-watch/',
       'https://azumbrunnen.me/blog/how-to-work-on-weekends-without-losing-your-soul-and-your-friends-the-1-charge-cycle/',
       'https://azumbrunnen.me/#contact',
       'https://azumbrunnen.me/blog/the-self-actualizing-designer/',
       'https://azumbrunnen.me/blog/transitions-in-ux-design/',
       'https://azumbrunnen.me/blog/interactive-float-labels/',
       'https://azumbrunnen.me/blog/building-progressively-enhanced-websites-with-bulletproof-backbone/',
       'https://azumbrunnen.me/blog/the-rise-of-anti-notifications/',
       'https://azumbrunnen.me/blog/creating-distraction-free-reading-experiences/',
       'https://azumbrunnen.me/blog/introducing-the-ux-bear/',
       'https://azumbrunnen.me/blog/what-designers-can-learn-from-the-iphone-x/',
       'https://azumbrunnen.me/blog/hover-states/',
       'https://azumbrunnen.me/blog/designing-with-purpose/',
       'https://azumbrunnen.me/blog/taking-responsibility-for-the-things-you-launch/'}}}
     ),
    ('http://fagaagfas.com', {}, 'http://fagaagfas.com', 1, {}),
])
def test_site_map_inside(url, map, domain, i, expected_result):
    result = site_map_inside(url, map, domain, i)
    assert result == expected_result
